// ignore_for_file: prefer_const_constructors, unnecessary_new

import 'package:flutter/material.dart';
class exploregrid extends StatelessWidget {
  final List<String>  myImage =[ 
     'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  
  'images/5.jpg','images/6.jpg',
   'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg',
   'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  
  'images/5.jpg','images/6.jpg',
   'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  
  'images/5.jpg','images/6.jpg',
   'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  
  'images/5.jpg','images/6.jpg',
   'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  
  'images/5.jpg','images/6.jpg',
   'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  
  'images/5.jpg','images/6.jpg',
   'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg',
   'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  
  'images/5.jpg','images/6.jpg',
   'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  
  'images/5.jpg','images/6.jpg',
   'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  
  'images/5.jpg','images/6.jpg',
   'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  
  'images/5.jpg','images/6.jpg',
   'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  
  'images/5.jpg','images/6.jpg',
   'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  
  'images/5.jpg','images/6.jpg',
   'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  
  'images/5.jpg','images/6.jpg',
   'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  
  'images/5.jpg','images/6.jpg',
   'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  
  'images/5.jpg','images/6.jpg',
   'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  
  'images/5.jpg','images/6.jpg',
   'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  
  'images/5.jpg','images/6.jpg',
   'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  
  'images/5.jpg','images/6.jpg',
   'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  
  'images/5.jpg','images/6.jpg',
   'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  
  'images/5.jpg','images/6.jpg',
   'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  
  'images/5.jpg','images/6.jpg',
   'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  
  'images/5.jpg','images/6.jpg',
   'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  
  'images/5.jpg','images/6.jpg',
   'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  
  'images/5.jpg','images/6.jpg',
   'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  
  'images/5.jpg','images/6.jpg',
   'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  
  'images/5.jpg','images/6.jpg',
   'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  
  'images/5.jpg','images/6.jpg',
   'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg', 'images/1.jpg',
  'images/2.jpg',
  'images/3.jpg',
  'images/4.jpg',
  'images/5.jpg','images/6.jpg',
  ];

  @override
  Widget build(BuildContext context) {
    return GridView.builder(
      gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: 3,
        crossAxisSpacing: 4.0,
        mainAxisSpacing: 4.0
      ),
      itemCount: myImage.length,
      itemBuilder: ( context,  index) {
        return  Padding(
          padding: const EdgeInsets.all(1.0),
          child: Container(
             decoration: BoxDecoration(
image: DecorationImage( image: AssetImage(myImage[index]),

           fit: BoxFit.cover    ),
               
                 ),

          //  color: Colors.purple[50],
          ),
        );
      },
    );
  }
}